version: "3"

services:
  app:
    build: ./docker/
    ports:
      - "80:80"
    volumes:
      - ./www/:/var/www/html      
    environment:
      - DB_PATH= 172.21.176.1:C:/administracao/db/MIAUTOMEC.FDB
      - DB_USER=SYSDBA
      - DB_PASSWORD=masterkey